### ISSUE TITLE
EPIC 2 -  User Story 1: Implement functionality to GET all activities for a particular user

### ISSUE THREAD

**Issue by therealadil** [SchoolOfCode/bc17-w4d2-project-teamac#3]
Description:

As Kenny, a busy front end engineer I need to be able to send a GET request with a user_id to the API to get a users activities so that I can make a nice simple dashboard that shows a user all of their activities.

As Norman, a Tech Lead working across lots of projects I need to be able to depend on conventions like: the response object always containing a key called data or error, or the status code being an accurate indication of the success/failure (and reason) of the request.

Acceptance Criteria:

Given I am a developer who has the Activity API running,
When I make a GET request to “http://localhost:3000/activities”

Then the the request should succeed, responding with the correct status code and an array of User Activity objects in the response body (response.data).
```[tasklist]
### Tasks
- [x] add new app.get with "/activities
- [x] create array object
- [x] send array object as response
```
